// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteModdedSprite(arg1) {
  return window['go']['main']['App']['DeleteModdedSprite'](arg1);
}

export function DeleteModdedSprites(arg1) {
  return window['go']['main']['App']['DeleteModdedSprites'](arg1);
}

export function ExportMod() {
  return window['go']['main']['App']['ExportMod']();
}

export function GetSpriteData() {
  return window['go']['main']['App']['GetSpriteData']();
}

export function GetSpriteGroup(arg1, arg2) {
  return window['go']['main']['App']['GetSpriteGroup'](arg1, arg2);
}

export function GetSpriteGroupData() {
  return window['go']['main']['App']['GetSpriteGroupData']();
}

export function GetSpritesByType(arg1) {
  return window['go']['main']['App']['GetSpritesByType'](arg1);
}

export function ProcessSprite(arg1, arg2) {
  return window['go']['main']['App']['ProcessSprite'](arg1, arg2);
}

export function ProcessSprites(arg1, arg2) {
  return window['go']['main']['App']['ProcessSprites'](arg1, arg2);
}
