// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteModdedSprite(arg1:main.Sprite):Promise<void>;

export function DeleteModdedSprites(arg1:Array<main.Sprite>):Promise<void>;

export function ExportMod():Promise<void>;

export function GetSpriteData():Promise<main.SpriteData>;

export function GetSpriteGroup(arg1:main.SpriteType,arg2:string):Promise<main.SpriteGroup>;

export function GetSpriteGroupData():Promise<main.SpriteGroupData>;

export function GetSpritesByType(arg1:main.SpriteType):Promise<Array<main.Sprite>>;

export function ProcessSprite(arg1:main.Sprite,arg2:main.ImageData):Promise<void>;

export function ProcessSprites(arg1:Array<main.Sprite>,arg2:main.ImageData):Promise<void>;
