// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportMod() {
  return window['go']['main']['App']['ExportMod']();
}

export function ProcessSpriteImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProcessSpriteImage'](arg1, arg2, arg3);
}

export function SpritePath(arg1) {
  return window['go']['main']['App']['SpritePath'](arg1);
}

export function SpritesDir() {
  return window['go']['main']['App']['SpritesDir']();
}

export function SpritesTree() {
  return window['go']['main']['App']['SpritesTree']();
}
