// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SpritePath(arg1) {
  return window['go']['main']['App']['SpritePath'](arg1);
}

export function SpritesDir() {
  return window['go']['main']['App']['SpritesDir']();
}

export function SpritesTree() {
  return window['go']['main']['App']['SpritesTree']();
}
