// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function SpritePath(arg1:main.Sprite):Promise<string>;

export function SpritesDir():Promise<main.Dir>;

export function SpritesTree():Promise<main.Tree>;
